// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-aDsU9oCrGjIN8xqQxAQEEnWPhopA464',
    appId: '1:121970113693:web:e4d9ed33cbb1bc1fb42874',
    messagingSenderId: '121970113693',
    projectId: 'airnests-app-39a0a',
    authDomain: 'airnests-app-39a0a.firebaseapp.com',
    storageBucket: 'airnests-app-39a0a.appspot.com',
    measurementId: 'G-4EB95SY08T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYd31JQpkRx0LJfW3jB_ByIFKYcUgMeI',
    appId: '1:319186034514:android:5d67ef8181af61d6fbe48b',
    messagingSenderId: '319186034514',
    projectId: 'airnest-7f402',
    storageBucket: 'airnest-7f402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv3FyH7zQ9EFdUQq4iGo3m1HIY0E3TszY',
    appId: '1:319186034514:ios:81b6fd35fa4b6fbffbe48b',
    messagingSenderId: '319186034514',
    projectId: 'airnest-7f402',
    storageBucket: 'airnest-7f402.appspot.com',
    iosBundleId: 'com.customer.airnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7m349251qflDsVIBOUfKYObazY66G2H8',
    appId: '1:121970113693:ios:b33688a584c6816eb42874',
    messagingSenderId: '121970113693',
    projectId: 'airnests-app-39a0a',
    storageBucket: 'airnests-app-39a0a.appspot.com',
    androidClientId: '121970113693-dj0irfp9522sfnk8lh37936506nanmn4.apps.googleusercontent.com',
    iosClientId: '121970113693-3t4e0nsgj7gtp6daqqrlvor82rh55lv5.apps.googleusercontent.com',
    iosBundleId: 'com.powermaid.airnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgK_YgWu8pUK2OvDEFTYm9FUy7osv2Peg',
    appId: '1:121970113693:web:d3291fa2596ae4f8b42874',
    messagingSenderId: '121970113693',
    projectId: 'airnests-app-39a0a',
    authDomain: 'airnests-app-39a0a.firebaseapp.com',
    storageBucket: 'airnests-app-39a0a.appspot.com',
    measurementId: 'G-YCW7NY3P74',
  );

}