part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const WELLCOME_SCREEN = _Paths.WELLCOME_SCREEN;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const VERICATION_OTP = _Paths.VERICATION_OTP;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const DESHBOARD = _Paths.DESHBOARD;
  static const CHAT_SCREEN = _Paths.CHAT_SCREEN;
  static const BOOKING_SCREEN = _Paths.BOOKING_SCREEN;
  static const NOTIFICATION_SCREEN = _Paths.NOTIFICATION_SCREEN;
  static const PROFILE_SCREEN = _Paths.PROFILE_SCREEN;
  static const HOME_SCREEN = _Paths.HOME_SCREEN;
  static const NOTIFICATION_DETAILS = _Paths.NOTIFICATION_DETAILS;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const MAID_DETAILS = _Paths.MAID_DETAILS;
  static const BOOK_APPOINTMENT = _Paths.BOOK_APPOINTMENT;
  static const CUSTOMER_INFORMATION = _Paths.CUSTOMER_INFORMATION;
  static const REVIEW_BOOKING_DETAIL = _Paths.REVIEW_BOOKING_DETAIL;
  static const BOOKING_SUMMARY = _Paths.BOOKING_SUMMARY;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const WALLET = _Paths.WALLET;
  static const ADD_ACCOUNT = _Paths.ADD_ACCOUNT;
  static const CHAT_LIST = _Paths.CHAT_LIST;
  static const LOCATION_SCREEN = _Paths.LOCATION_SCREEN;
  static const CLEANER_BIDS_LIST = _Paths.CLEANER_BIDS_LIST;
  static const NEW_CLEANER_BIDS_LIST = _Paths.NEW_CLEANER_BIDS_LIST;
  static const BIDER_DETAIL_SCREEN = _Paths.BIDER_DETAIL_SCREEN;
  static const SIGN_UP_BASIC_DETAILS_SCREEN =
      _Paths.SIGN_UP_BASIC_DETAILS_SCREEN;
  static const MAKE_ACCOUNT_WITH_SCREEN = _Paths.MAKE_ACCOUNT_WITH_SCREEN;
  static const CONGRATS_SCREEN = _Paths.CONGRATS_SCREEN;
  static const SIGN_UP_VERIFY_OTP = _Paths.SIGN_UP_VERIFY_OTP;
  static const CREATE_BID_SUMMARY = _Paths.CREATE_BID_SUMMARY;
  static const HELP_SCREEN = _Paths.HELP_SCREEN;
  static const MY_FAVOURITE = _Paths.MY_FAVOURITE;
  static const VERIFY_CHANGE_PASSWORD = _Paths.VERIFY_CHANGE_PASSWORD;
  static const RESET_CHANGE_PASSWORD = _Paths.RESET_CHANGE_PASSWORD;
  static const SAVED_CARD = _Paths.SAVED_CARD;
  static const CHAT_BOD_SCREEN = _Paths.CHAT_BOD_SCREEN;
  static const CHAT_BOD_VERIFY = _Paths.CHAT_BOD_VERIFY;
  static const CHATBOOTVERIFY_OTP = _Paths.CHATBOOTVERIFY_OTP;
  static const PAYMENT_SUCCESSFUL_SCREEN = _Paths.PAYMENT_SUCCESSFUL_SCREEN;
  static const FILTER_SCREEN = _Paths.FILTER_SCREEN;
  static const RECOMMENDED_VIEW_ALL = _Paths.RECOMMENDED_VIEW_ALL;
  static const SEARCH_CLEANERS = _Paths.SEARCH_CLEANERS;
  static const EXTRAWORK_ADD_SCREEN = _Paths.EXTRAWORK_ADD_SCREEN;
  static const TRACK_YOURCLEANER_SCREEN = _Paths.TRACK_YOURCLEANER_SCREEN;
  static const SELECT_SERVICES = _Paths.SELECT_SERVICES;
  static const BOOKING_DETAIL = _Paths.BOOKING_DETAIL;
  static const CLEANER_And_Cohost_LIST = _Paths.CLEANER_And_Cohost_LIST;
  static const PHOTO_VIEW_MAID_DETAILS = _Paths.PHOTO_VIEW_MAID_DETAILS;

  static const ADD_PROPERTY_SCREEN = _Paths.ADD_PROPERTY_SCREEN;
  static const CREATE_BID_FOR_CLEANER_AND_COHOST =
      _Paths.CREATE_BID_FOR_CLEANER_AND_COHOST;
  static const ADD_REQUIREMENT_CLEANER = _Paths.ADD_REQUIREMENT_CLEANER;
  static const ADD_REQUIREMENT_CREATE_BID = _Paths.ADD_REQUIREMENT_CREATE_BID;
  static const ADD_REQUIREMENT_CLEANER_SUMMERY =
      _Paths.ADD_REQUIREMENT_CLEANER_SUMMERY;
  static const WRITEREVIEW = _Paths.WRITEREVIEW;
  static const BLOGSSCREEN = _Paths.BLOGSSCREEN;
  static const BLOGSDETAILS = _Paths.BLOGSDETAILS;
  static const VIDEO_CALL = _Paths.VIDEO_CALL;
  static const AUDIO_CALL = _Paths.AUDIO_CALL;
  static const BIDSUMMARYBOOKING = _Paths.BIDSUMMARYBOOKING;
  static const CONNECTIVITY_SCREEN = _Paths.CONNECTIVITY_SCREEN;
  static const TERMS_AND_CONDITIONS = _Paths.TERMS_AND_CONDITIONS;
  static const CONTACT_US = _Paths.CONTACT_US;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const WELLCOME_SCREEN = '/wellcome-screen';
  static const SIGN_IN = '/sign-in';
  static const SIGN_UP = '/sign-up';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const VERICATION_OTP = '/verication-otp';
  static const RESET_PASSWORD = '/reset-password';
  static const DESHBOARD = '/deshboard';
  static const CHAT_SCREEN = '/chat-screen';
  static const BOOKING_SCREEN = '/booking-screen';
  static const NOTIFICATION_SCREEN = '/notification-screen';
  static const PROFILE_SCREEN = '/profile-screen';
  static const HOME_SCREEN = '/home-screen';
  static const NOTIFICATION_DETAILS = '/notification-details';
  static const CHANGE_PASSWORD = '/change-password';
  static const MAID_DETAILS = '/maid-details';
  static const BOOK_APPOINTMENT = '/book-appointment';
  static const CUSTOMER_INFORMATION = '/customer-information';
  static const REVIEW_BOOKING_DETAIL = '/review-booking-detail';
  static const BOOKING_SUMMARY = '/booking-summary';
  static const EDIT_PROFILE = '/edit-profile';
  static const WALLET = '/wallet';
  static const ADD_ACCOUNT = '/add-account';
  static const CHAT_LIST = '/chat-list';
  static const LOCATION_SCREEN = '/location-screen';
  static const CLEANER_BIDS_LIST = '/cleaner-bids-list';
  static const NEW_CLEANER_BIDS_LIST = '/new-cleaner-bids-list';
  static const BIDER_DETAIL_SCREEN = '/bider-detail-screen';
  static const SIGN_UP_BASIC_DETAILS_SCREEN = '/sign-up-basic-details-screen';
  static const MAKE_ACCOUNT_WITH_SCREEN = '/make-account-with-screen';
  static const CONGRATS_SCREEN = '/congrats-screen';
  static const SIGN_UP_VERIFY_OTP = '/sign-up-verify-otp';
  static const CREATE_BID_SUMMARY = '/create-bid-summary';
  static const HELP_SCREEN = '/help-screen';
  static const MY_FAVOURITE = '/my-favourite';
  static const VERIFY_CHANGE_PASSWORD = '/verify-change-password';
  static const RESET_CHANGE_PASSWORD = '/reset-change-password';
  static const SAVED_CARD = '/saved-card';
  static const CHAT_BOD_SCREEN = '/chat-bod-screen';
  static const CHAT_BOD_VERIFY = '/chat-bod-verify';
  static const CHATBOOTVERIFY_OTP = '/chatbootverify-otp';
  static const PAYMENT_SUCCESSFUL_SCREEN = '/payment-successful-screen';
  static const FILTER_SCREEN = '/filter-screen';
  static const RECOMMENDED_VIEW_ALL = '/recommended-view-all';
  static const SEARCH_CLEANERS = '/search-cleaners';
  static const EXTRAWORK_ADD_SCREEN = '/extrawork-add-screen';
  static const TRACK_YOURCLEANER_SCREEN = '/track-yourcleaner-screen';
  static const SELECT_SERVICES = '/select-services';
  static const BOOKING_DETAIL = '/booking-detail';
  static const CLEANER_And_Cohost_LIST = '/cleaner_and_cohost_lIST';
  static const PHOTO_VIEW_MAID_DETAILS = '/photo-view-maid-details';
  static const ADD_PROPERTY_SCREEN = '/add-property-screen';
  static const CREATE_BID_FOR_CLEANER_AND_COHOST =
      '/create-bid-for-cleaner-and-cohost';
  static const ADD_REQUIREMENT_CLEANER = '/add-requirement-cleaner';
  static const ADD_REQUIREMENT_CREATE_BID = '/add-requirement-create-bid';
  static const ADD_REQUIREMENT_CLEANER_SUMMERY =
      '/add-requirement-cleaner-summery';
  static const WRITEREVIEW = '/writereview';
  static const BLOGSSCREEN = '/blogs-screen';
  static const BLOGSDETAILS = '/blogs-details';
  static const VIDEO_CALL = '/video-call';
  static const AUDIO_CALL = '/audio-call';
  static const BIDSUMMARYBOOKING = '/bid-summary-booking';
  static const CONNECTIVITY_SCREEN = '/connectivity-screen';
  static const TERMS_AND_CONDITIONS = '/terms-and-conditions';
  static const CONTACT_US = '/contact-us';
}
